apiVersion: apps/v1
kind: Deployment
metadata:
  name: knodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knodeapp
  template:
    metadata:
      labels:
        app: knodeapp
    spec:
      containers:
      - name: knodeapp
        image: luisaguilar03/eneronodeapp2:<IMAGE_TAG>
        ports:
          - containerPort: 3000