apiVersion: apps/v1
kind: Deployment
metadata:
  name: knodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knodeapp
  template:
    metadata:
      labels:
        app: knodeapp
    spec:
      containers:
      - name: knodeapp
        image: luisaguilar03/eneronodeapp2:<IMAGE_TAG>
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: knodeapp-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: knodeapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knodeapp-ingress
  annotation:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - aguachile.molcajete.dev
      secretName: letsencrypt-ngnix
  rules:
  - host: aguachile.molcajete.dev
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: knodeapp-service
            port:
              number: 3000
      
