apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knodeapp
  namespace: devops 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: knodeapp
  template:
    metadata:
      labels:
        app: knodeapp
    spec:
      containers:
      - name: knodeapp
        image: luisaguilar03/eneronodeapp2:<IMAGE_TAG>
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: knodeapp-service
  namespace: devops
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: knodeapp
